### PR TITLE
Replace istanbul with nyc

### PR DESCRIPTION
**Pull request by laggingreflex**
better cross-platform support and shorter command syntax

https://github.com/istanbuljs/nyc/

### CODE REVIEW

**Comment by laggingreflex** [comment]
Hmm no idea why it's failing. It works locally.

**Comment by joelgriffith** [comment]
I like this a lot better than old `istanbul`, but it's failing the build:

https://travis-ci.org/appnexus/sicksync/builds/173604219

**Comment by joelgriffith** [comment]
@laggingreflex try altering the `test` in your PR to: `nyc --reporter=lcov --reporter=text --include 'src/local/*' --include 'src/remote/*' npm run mocha`

**Comment by laggingreflex** [comment]
It worked! 

So this works:
```json
"test": "nyc --reporter=lcov --reporter=text --include 'src/local/*' --include 'src/remote/*' npm run mocha",
```
but this doesn't:
```json
"test": "nyc --reporter=lcov --reporter=text --include src/**/* --exclude test/**/*.mspec.js npm run mocha",
```
While both work on my Windows, but it seems only the first one works on *nix (including bash-on-windows). 

It can't be globbing issue, right? cause mocha statement is still using unquoted globs:
```json
"mocha": "mocha test/**/*.mspec.js --compilers js:babel-register",
```
Must be an nyc issue...

**Comment by joelgriffith** [comment]
Yup, likely some odd bug in the way it parses argument input... Either way, thanks for finding this!

**Pull request merged**
